[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
reqwest = "0.12"
tracing = { version="0.1", features = ["log"] }
reqwest-middleware = "0.3"
rust-argon2 = "1.0"
